server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html;

    client_max_body_size 100m;

    location ~ ^/show/([0-9]+)/?$ {
        rewrite ^/show/([0-9]+)/?$ /show.php?id=$1 last;
    }

    location = / {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/src/Public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param HTTP_PROXY "";
        fastcgi_pass 127.0.0.1:9000;
    }

    location / {
        try_files $uri =404;
    }

    location ~ ^/(index|show|download|delete)\.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/src/Public/$1.php;
        fastcgi_param SCRIPT_NAME /$1.php;
        fastcgi_param HTTP_PROXY "";
        fastcgi_index index.html;
        fastcgi_pass 127.0.0.1:9000;
    }

    location ~ ^/(?:app/)?api/(upload|verifydownload|verifydelete)\.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/src/Public/api/$1.php;
        fastcgi_param SCRIPT_NAME /api/$1.php;
        fastcgi_param HTTP_PROXY "";
        fastcgi_pass 127.0.0.1:9000;
    }

    location ^~ /src/ {
        deny all;
    }

    location ~ \.php$ {
        return 404;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
